# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EVB+YSAnDWq2BcACH5h/pPeaDouE8GQQ8uUiw8kwzxfgzDAFCQARx5a1PDc+/i3FlQSROPlP8xDArQbkiSC0xbYzh6tLJhM3C6ST/t8Uyp16/QpsebnwkGbKy9IJM8h6IWSNxj4QoweIFc08SXd+kGn4spi8WJJpVvReHTcY0dgUt9HfuN6rziDYxykVtm9/oLOAqcNXZXkCi9hUITPhBpZZQ9KOBhHNaiiY/1yBJbdYxknLcsWFwDB/gKssHgH7m78njO84bjuH4El73kWTEP9uXIWW3rCwV5wV4RID4GP7rZgtAZQbpSUWyAM8iZI7YML7sp3d9gsELjcikZHZc1Sf/fekah9lnNSPmtC+TwuEicAIcd4x+V4KZe3uxO3OdZSU5yjM+K9t1whtk5W03dj/MysAWI/8X003nwbFlbrFsY+advLUd2fDOh1RZ+/OWPwDxJiLMth46MOr890Y8455is0TvtHMeQQaSO/ynplWTII4VTuzpjFfP5BMQzn6aMyIJYLy+7g/qh64MrT4WBqjVo4fp+bhV54Z/E6VPsjyUa+AJ367+tuPTw1hzLFkzLXREw8LpFJaiEEajJY9n0EsfRsQWY7iXSHlx00gBqM1HLO29GgRfemQwcuKX3dUzdv8jVOhf2zvzdLX2qih+Th1O3bCz3Xri9fr90p9YFM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
