travis:
  secure:
    BINSTAR_TOKEN: NxlDyxCVKcfY+XMaBKUKK2TNHVJxmO3T1W9FGszCto59Fhc2Be/QJjzC2NiaHMW9JdfLau9qC0mfF3k5noA7eDrzxuBGGNHSvVftI0HfAEvNfhTDQqvia66vfgI9edzlU5Hol2wy1DFVEWrLa46SNgUpBWaYvy1dLgABYgrDfKtUchAwy7lh07ixGbE6f4xhTX92k/IR3lZz2v/ZuD2bj8BFMyRveJoeDxa+YjJLNa3bcjZjbfJrjk2u28EiPTkjeOmDywsftoQQ/7w3h8I6MQ3YoxjNEewdZG5ej0Ofrc6jYOZcV5P6OHTmgg2i0Hq32mRVIJLc3KTcF5z1TBY15ZuP+EOEL8b25CtWNTUJnUDzcfNbhskysakmI2PhALQWQR3xFoefBHYKagouTY4v92JR+yx95VWpIau39MyRquNuebCxJ0uJAkUAiieAx/ldnOr2SAElvTP6rgsmZSb9V9L4cGSL8VmhUu2u1Ds4el4MOWZhvz0FSFcMRR8aFoDxX2lnoyGQGSBN1RNNSAPbV3sQBeKXFGojCIcrYHaiAnPPNk5eJHqOyofUw6F7VCxxOW6jcVCqVdIfUiQT0KzZT9fEg/mcCeTZe0HDJYV+6sXPRCfhSkgAMF3TeXGb8mnhF1vErIKa8obw7LnDSk5eTuRpfrn107dhEoVLKaTVi5c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
