travis:
  secure:
    BINSTAR_TOKEN: EVB+YSAnDWq2BcACH5h/pPeaDouE8GQQ8uUiw8kwzxfgzDAFCQARx5a1PDc+/i3FlQSROPlP8xDArQbkiSC0xbYzh6tLJhM3C6ST/t8Uyp16/QpsebnwkGbKy9IJM8h6IWSNxj4QoweIFc08SXd+kGn4spi8WJJpVvReHTcY0dgUt9HfuN6rziDYxykVtm9/oLOAqcNXZXkCi9hUITPhBpZZQ9KOBhHNaiiY/1yBJbdYxknLcsWFwDB/gKssHgH7m78njO84bjuH4El73kWTEP9uXIWW3rCwV5wV4RID4GP7rZgtAZQbpSUWyAM8iZI7YML7sp3d9gsELjcikZHZc1Sf/fekah9lnNSPmtC+TwuEicAIcd4x+V4KZe3uxO3OdZSU5yjM+K9t1whtk5W03dj/MysAWI/8X003nwbFlbrFsY+advLUd2fDOh1RZ+/OWPwDxJiLMth46MOr890Y8455is0TvtHMeQQaSO/ynplWTII4VTuzpjFfP5BMQzn6aMyIJYLy+7g/qh64MrT4WBqjVo4fp+bhV54Z/E6VPsjyUa+AJ367+tuPTw1hzLFkzLXREw8LpFJaiEEajJY9n0EsfRsQWY7iXSHlx00gBqM1HLO29GgRfemQwcuKX3dUzdv8jVOhf2zvzdLX2qih+Th1O3bCz3Xri9fr90p9YFM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
