travis:
  secure:
    BINSTAR_TOKEN: AcExxL8DzcVuA1vkQ29xuWzLyCvqTHvWxqJLgNFVNyOzK7ablyGjOPUGjQ4wFFUIyu/5ZZiH4KIRoy9rSfM6ngiClO6VGb16a9y4oZDOFuRejq/y4PCX4tgb2K01YhAVGfnnCZKRrZJRoY1I7MZpe31lAktNH+SdABcKHZojS4TOvoVPWRlJC1lKirH3Oq6vtqCCBMOO1hUnB0LZn50zRQYd2awn484MOt2gOs5cMlyWXR0jknwYwxxW1k+noMjs0W8mdQxEyqYskcyerAS9ZpRfRndgghUq5UvHgDwQ1ikAhNAOdbxUO4+4LzQy514HNrb9fKzBVYD6hiDHwd+uVDBxhqqhu+VDoCZ41v2E79jKxuU/RE06WbER0mzyA26Nd7Nsq89YrKuztP3gYHwySyPq7xnc2XxQf7Y/I2VS0VGPWfls3HaWOLWHR4sVAXKjTjiVf4knyl8aIR36UHU8Fvm3Fem8TTzgYZM3+YAOXn7Aze6nbkfBssI0dtWq0/bmOuE+Bf1Tf4RnnT3HbW/DURtyLmDKJ4fHj8CjQW/1NsIvdZqj2JrRxakU2pP/6lOhfHOqSv+XEJysMzgTwx/A4O11eXZzrnA+ZQUs1gy/RuGtpMyXTQdeKu+OYUI806xib4ztmW7e0Xc0rPydQQp674LQpgEhLBAmEzcTPzUnb0w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
