travis:
  secure:
    BINSTAR_TOKEN: ONLrlpBG1CgXxdEfmPYZsB816JQoZqHb3bo2AUcMhYL12FIfxahGesHQwEh1DcLtKXqOcEehlQwyBaBtYJDnq8h3pf7wvnFB29I4SPt3gFcQMxfsSF5Crn3UnasAMpfrVgA0mlrMAqFjN2ObJgfQ8oDq6dErSrehcLvKsCdco0n1w4bFedJXxae4khaFkZi+fSuflW8CM+V4DEW6JvEA0bV1YWiCoIl6J5JvWVH8RqbhUwVAMUw+Tibon54G7Pad8ff5wNF7WX5r7STTQNZpcqZydgscMEPIp9NE0vg5vdH7R7l2Qa0fjyP+WyTM5bhyMWNjAnB81iSBrivd9DO9hwt3xK7upZDZTJOFLz24pOqntABtaTsPNbRaBPLZuR7x/ym9ZEzwIJaMGb+/CIUHJsICLPW6wxibxtRY2IWX6qrEZXuAcGQAYiPFzCSgMpUIgqzfYAW4xByBWcxYmFiXbbIk1N83lxq6Ip0PDNlx1cGx5lW5ZHfjb2CwcX46/hxapPL/rtRYfdl6Eyjx3brbDXmQtgd2OrNARPULK937h06eY8h+B9QbPU5p6JUQV+9sYp+70ozYLDlsdFkhO36A65oR/UphyLZLO5JVWekFmrkNDxQzDqJLw9w/XMssEa+PDnPiYyTHShi41uy925h2AlhrsJar6u5p2N+LTqNMI5g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
