travis:
  secure:
    BINSTAR_TOKEN: ikkXzwqn0dHcN1yEtT17L7N5A2NSggmNJTHAYzmTit77hkEgNZtoOoJZm2NBzS8MSmfb7/rwEWrSrC7+jT9Lodi3dFF9jexCFQShejU90YlgT70j19xHQStQ5ttWV7xJ8JfF7lJgT3tVAo4Tlf7ERlQNzhdsk9klB1RoYFEUP0HIfnqTKKx8pKjLv1B4SuUZH5pcxD+8wzWq/keyO+uGvE5btbVbyEszh0tZVi9BdBx9mNxLusyWKMuowKk4Z9B27f2R5/Ms38Q455GafJA58AYfULqGdK2Wnu94Tn8cnI3JkbUFkhF9MXTiZBz2gHTxijrLvfPV4HWW4k0b1CrFL279NVEbsr2J0awLbbs0KofIEsoZu61+zN5QxHNYBn+Wwrpyn6tCNwHh7LDvqy2nVhYaodT6knwmU8EnkgNLPfdt6vVlbH7Ehj5bZv/zg6U6TiWJ0PSpIkTLBSlhxRacSTjoarDBKnWGfRCycrbDGc72o7CutBPz1KxrzzXDDhURB0vA9imCzqGGaxE69iC7oRG9PfHKxNIXCJvWje6v0cZLNTELMnM+s/z0sPnIsrESU50PKpjSISva2xs3sQM91yEQtHrKox4c0EtQSvn6IWKn+aeix44Qzh44SDYmPyVXwXSsZ3bK+ONDSUNgisIiwzQeHeqffAjxJdVbBUwYCZw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
