travis:
  secure:
    BINSTAR_TOKEN: ATOYQabWIAHoRgBDStqxyRb01LUPJAkj9/T46NmvkXO7HfMQ3u74FX845R4/Afg5aS+hV5AyK4LSo+zSP2qV2bdoxSGxhwD/gBzDnboiYCnzDROiD4BAB19JdGnSx7Pis+mzljGLBBiVWOuNmPyHc0AzBbWcxWnUeaIgXrP/Pp1E5X0LMC06l07lffo4RgNez17KHB+fLpYps9DP/CxaUaPAChslYJEujd/F/bvcsdfEVZue3wIRF8eBPsYH1CdyAK3A1E86G18d+j6XA+njPAsDY//mI9XAmhgxrvzdFnIZx3kDZWM6exuML+9CS4usY7nexW6IktBOpfCk5ULqU1uYpnHMJAtMWHItTQqFi1GVWu/eMp+l56nkmTf8xInAoKX7b8bLvJnVZIta5UMdApGZTy5luZtmwJ2CaEhxoPLqrICgFOUy8wqfTkpQBq2jVap7qhqXOcrsuBGax78AR8QqQ6IJt+y0gM6xbo/eXxzcK4KvOqghxkoxN3zpIykUeYmeQQGKyyP8WgyRW6nAKE/XUZwpyvIvRFaOfYJ21fZOt3Q8e2PT8MTDoJFKYp09Z4RB3KX3XDV44LEEqIftbDZdWrk6UG7A13ogJmhbqxmnQAcDjjY8VWumDF61FrUTVfjguwvtN366L1s7P+LGtuLpQtLYen4NPtM0QCFG5QY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
